import type { PaginationParams } from "@/shared/types/api.types";

export interface StartConversationDto {
  participantId: string;
}

export interface ConversationParticipant {
  id: string;
  name?: string;
  avatar?: string;
  role?: string;
  lastSeenAt?: string | null;
}

export interface Conversation {
  id: string;
  participants: ConversationParticipant[];
  lastMessage: Message | null;
  lastMessageAt: string;
  /** Messages from the other participant not yet seen. Server is source of truth. */
  unreadCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export type MessageKind = "text" | "resource" | "post";

/** Server-resolved snapshot of the item a message is about (BACKLOG.md E13). */
export interface MessageContext {
  refId: string;
  title: string;
  subtitle?: string;
}

/** An item the composer will attach to the next message. */
export interface ChatAttachment {
  kind: Exclude<MessageKind, "text">;
  contextId: string;
  title: string;
  subtitle?: string;
}

export interface CreateMessageDto {
  conversationId: string;
  content: string;
  clientId: string; // generated by client, echoed back in server replica
  /** Omitted for plain text. `contextId` is required when set. */
  kind?: MessageKind;
  contextId?: string;
}

/** What callers pass to send/retry — the hook supplies `clientId`. */
export type SendMessageDto = Omit<CreateMessageDto, "clientId">;

export interface DeleteMessageDto {
  messageId: string;
  conversationId: string;
}

export interface GetMessagesParams extends PaginationParams {
  conversationId: string;
  before?:string;
}

export interface Message {
  clientId: string;
  id: string;
  conversationId: string;
  sender: string;
  content: string;
  kind?: MessageKind;
  context?: MessageContext;
  seenAt: Date | null;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;

  _status?: "PENDING" | "SENT" | "FAILED";
}

export interface MarkSeenDto {
  conversationId: string;
  seenBy: string;
}

export interface PresenceEvent {
  userId: string;
  online: boolean;
  lastSeenAt?: string;
}

export interface TypingEvent {
  conversationId: string;
  userId: string;
  isTyping: boolean;
}
