import type { PaginationParams } from "@/shared/types/api.types";

export interface StartConversationDto {
  participantId: string;
}

export interface ConversationParticipant {
  id: string;
  name?: string;
  avatar?: string;
  role?: string;
  lastSeenAt?: string | null;
}

export interface Conversation {
  id: string;
  participants: ConversationParticipant[];
  lastMessage: Message | null;
  lastMessageAt: string;
  /** Messages from the other participant not yet seen. Server is source of truth. */
  unreadCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export type MessageKind = "text" | "resource" | "post";

/** Item a message is about, rendered as a card (BACKLOG.md E13). */
export interface MessageContext {
  title: string;
  subtitle?: string;
}

/** An item staged to be attached to the next message sent. */
export interface ChatAttachment extends MessageContext {
  kind: Exclude<MessageKind, "text">;
  id: string;
}

export interface CreateMessageDto {
  conversationId: string;
  content: string;
  clientId: string; // generated by client, echoed back in server replica
  kind?: MessageKind;
  /** Required when `kind` is not "text". */
  contextId?: string;
}

/** What a caller supplies to send (or retry) a message. */
export type SendMessageInput = Omit<CreateMessageDto, "clientId">;

export interface DeleteMessageDto {
  messageId: string;
  conversationId: string;
}

export interface GetMessagesParams extends PaginationParams {
  conversationId: string;
  before?:string;
}

export interface Message {
  clientId: string;
  id: string;
  conversationId: string;
  sender: string;
  content: string;
  kind?: MessageKind;
  contextId?: string | null;
  context?: MessageContext | null;
  seenAt: Date | null;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;

  _status?: "PENDING" | "SENT" | "FAILED";
}

export interface MarkSeenDto {
  conversationId: string;
  seenBy: string;
}

export interface PresenceEvent {
  userId: string;
  online: boolean;
  lastSeenAt?: string;
}

export interface TypingEvent {
  conversationId: string;
  userId: string;
  isTyping: boolean;
}
